#!/bin/bash
set -euo pipefail

mysql --protocol=socket -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS nacos_config CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS docbase_iam CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS docbase_knowledge CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS docbase_ingest CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS docbase_chat CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS docbase_rag CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

CREATE USER IF NOT EXISTS '${NACOS_DB_USER}'@'%' IDENTIFIED BY '${NACOS_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${IAM_DB_USER}'@'%' IDENTIFIED BY '${IAM_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${KNOWLEDGE_DB_USER}'@'%' IDENTIFIED BY '${KNOWLEDGE_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${INGEST_DB_USER}'@'%' IDENTIFIED BY '${INGEST_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${CHAT_DB_USER}'@'%' IDENTIFIED BY '${CHAT_DB_PASSWORD}';
CREATE USER IF NOT EXISTS '${RAG_DB_USER}'@'%' IDENTIFIED BY '${RAG_DB_PASSWORD}';

GRANT ALL PRIVILEGES ON nacos_config.* TO '${NACOS_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON docbase_iam.* TO '${IAM_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON docbase_knowledge.* TO '${KNOWLEDGE_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON docbase_ingest.* TO '${INGEST_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON docbase_chat.* TO '${CHAT_DB_USER}'@'%';
GRANT ALL PRIVILEGES ON docbase_rag.* TO '${RAG_DB_USER}'@'%';
FLUSH PRIVILEGES;
SQL
